---
- hosts: all
  roles:
    - role: packages
      tags:
        - packages
        - shell
        - desktop
    - role: fonts
      tags:
        - fonts
        - desktop
    - role: gnome
      tags:
        - gnome
        - desktop
    - role: luyz25.gnome_extensions
      vars:
        gnome_extension_ids:
          - 19
          - 615
      tags:
        - gnome_extensions
        - desktop
    - role: bash
      tags:
        - bash
        - shell
    - role: vim
      tags:
        - editor
        - shell
      vars:
        deploy_to_users: [ hayden ]
    - role: gh_cli
      tags:
        - gh_cli
        - shell
    - role: mpd
      tags:
        - mpd
        - desktop
