#!/usr/bin/env bash

system_type="$(uname -s)"

if [[ "$system_type" = "Darwin" ]]; then
    bash "$HOME/.config/yadm/bootstrap-darwin.sh"
elif [[ "$system_type" = "Linux" ]]; then
    \. /etc/os-release
    if [[ "$ID" = "fedora" ]]; then
        echo "Running Fedora"
        bash "$HOME/.config/yadm/bootstrap-fedora.sh"
    elif [[ "$ID" = "arch" ]]; then
        echo "Running Arch Linux"
        bash "$HOME/.config/yadm/bootstrap-arch.sh"
    else
        echo "Unsupported Linux distro. Not bootstrapping."
        exit 1
    fi
fi
