---
- name: Ensure Bash is installed
  become: true
  package:
    name: bash,bash-completion
    state: present

- name: Install util-linux-user
  become: true
  when: ansible_distribution == 'Fedora'
  package:
    name: util-linux-user
    state: present

- name: Set Bash as this user's current shell
  become: true
  command: chsh -s /bin/bash {{ ansible_env.USER }}
  register: bash_for_user
  failed_when: bash_for_user.rc >= 1
  changed_when: bash_for_user.rc == 0

- name: Install custom bashrc
  when: not install_remote
  file:
    src: "{{ role_path }}/files/bashrc.bash"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    state: link

- name: Install custom bashrc
  when: install_remote
  ansible.builtin.copy:
    src: "{{ role_path }}/files/bashrc.bash"
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: 0644

- name: Create bashrc.d folder
  file:
    path: "{{ ansible_env.HOME }}/.config/bashrc.d"
    mode: 0755
    state: directory

- name: Install custom aliases
  when: not install_remote
  file:
    src: "{{ role_path }}/files/aliases.bash"
    dest: "{{ ansible_env.HOME }}/.config/bashrc.d/aliases.bash"
    state: link

- name: Install custom aliases
  when: install_remote
  copy:
    src: "{{ role_path }}/files/aliases.bash"
    dest: "{{ ansible_env.HOME }}/.config/bashrc.d/aliases.bash"
    mode: 0644
