---
- name: 'Install GitHub CLI Yum Repo'
  when: ansible_facts['os_family'] == 'RedHat'
  become: true
  get_url:
    url: 'https://cli.github.com/packages/rpm/gh-cli.repo'
    dest: '/etc/yum.repos.d/gh-cli.repo'

- name: 'Install GitHub CLI'
  when: ansible_distribution != 'ArchLinux'
  become: true
  package:
    name: 'gh'
    state: 'present'

- name: 'Install GitHub CLI'
  when: ansible_distribution == 'ArchLinux'
  become: true
  package:
    name: 'github-cli'
    state: 'present'

