#  _   ___  __
# | |_| \ \/ /
# |  _  |\  /   hbjydev's tmux config
# |_| |_|/_/
#

######[ KEYBINDS ]######

# set control keybinding to C-a
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# prefix + | to horizontally split window
unbind %
bind | split-window -h -c "#{pane_current_path}"

# prefix + - to vertically split window
unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# prefix + c to open a new window
bind c new-window -c "#{pane_current_path}"

# vim-like keybinds to resize windows
bind -r H resize-pane -L 5 # resize 5px bigger to the left
bind -r J resize-pane -D 5 # resize 5px bigger to the left
bind -r K resize-pane -U 5 # resize 5px bigger to the left
bind -r L resize-pane -R 5 # resize 5px bigger to the left

# reload config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded tmux config!"


######[ INTERFACE ]######

# style the status bar
set -g status-style fg="default",bg="black"

set -g status-left '#[fg=black] #S #I/#P '
set -g status-left-style bg="magenta"

set -g status-right '#[fg=magenta]#h '

# style the window status
set -g status-justify centre
set -g window-status-style fg="default",bg="black"
set -g window-status-format "[ #I: #W ]"
set -g window-status-current-style fg="magenta",bg="black"
set -g window-status-current-format "[ #I: #W ]"

# colour the message bar
set -g message-style fg="black",bg="magenta"

# colour the borders
set -g pane-border-style fg=colour232,bg=black
set -g pane-active-border-style fg=default,bg=black

######[ MISCELLANEOUS ]######

# use 256-bit colour
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# increase scroll-back history
set -g history-limit 5000

# start window index at 1 instead of 0
set -g base-index 1

# start pane index at 1 instead of 0
setw -g pane-base-index 1

# highlight window when it has new activity
setw -g monitor-activity on
set -g visual-activity on

# re-number windows when one is closed
set -g renumber-windows on
