---
- name: Install required packages
  become: true
  package:
    name: fzf,git,vim
    state: installed

- name: Install Node.js for Coc.nvim
  become: true
  shell: |
    which node || curl -sL install-node.now.sh/lts | sh -s -- -y

- with_items: "{{ deploy_to_users }}"
  include: install.yml

