---
- name: Ensure tmux is installed
  become: true
  package:
    name: tmux
    state: present

- name: Install tmux configuration file
  copy:
    src: files/tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0644
    backup: true
