---
- name: Ensure .config/nvim/{autoload,bundle} directories exist
  file:
    path: '{{ item }}'
    state: directory
    recurse: false
    mode: 0750
  with_items:
    - '{{ vim_config_dir }}'
    - '{{ vim_data_dir }}'
    - '{{ vim_data_dir }}/autoload'
    - '{{ vim_data_dir }}/bundle'

- name: Ensure Pathogen is installed
  get_url:
    dest: '{{ vim_data_dir }}/autoload/pathogen.vim'
    url: 'https://tpo.pe/pathogen.vim'

- name: Deploy plugins
  git:
    dest: '{{ vim_data_dir }}/bundle/{{ item.name }}'
    repo: '{{ item.url }}'
    clone: true
    update: true
    recursive: false
  with_items: '{{ plugins }}'

- name: Deploy vimrc
  copy:
    src: vimrc.vim
    dest: '{{ vimrc }}'
    backup: true
    mode: 0640
