---
- name: Install required packages
  become: true
  package:
    name: fzf,git,vim
    state: installed

- name: Install Node.js LTS for Coc.nvim
  become: true
  shell: |
    curl -sL install-node.now.sh/lts | sh -s -- -y

- name: Ensure .vim/{autoload,bundle} directories exist
  file:
    path: '{{ item }}'
    state: directory
    recurse: false
    mode: 0750
  loop:
    - "{{ vim_dir }}"
    - "{{ vim_dir }}/autoload"
    - "{{ vim_dir }}/bundle"

- name: Ensure Pathogen is in place
  get_url:
    dest: "{{ vim_dir }}/autoload/pathogen.vim"
    url: https://tpo.pe/pathogen.vim

- name: Deploy plugins
  git:
    dest: "{{ vim_dir }}/bundle/{{ item.name }}"
    repo: "{{ item.url }}"
    clone: true
    update: true
    recursive: false
  loop: "{{ plugins }}"

- name: Deploy vimrc file
  copy:
    src: vimrc.vim
    dest: "{{ vimrc }}"
    backup: true
    mode: 0640

