---
- name: Install required packages
  become: true
  package:
    name:
      - fzf
      - git
      - vifm
      - ninja-build
      - libtool
      - autoconf
      - automake
      - cmake
      - gcc
      - gcc-c++
      - make
      - pkgconfig
      - unzip
      - patch
      - python3-neovim
    state: installed

- name: Unpacking neovim
  unarchive:
    copy: false
    dest: /tmp/
    src: "https://github.com/neovim/neovim/archive/master.tar.gz"

- name: Installing neovim
  become: true
  shell: make && make install
  args:
    chdir: "/tmp/neovim-master"

- name: Install pip packages
  become: true
  pip:
    name:
      - neovim
      - neovim-remote

- name: Install neovim npm package
  become: true
  npm:
    name: neovim
    global: true

- name: Check if Node.js is installed
  command: which node
  register: node_installed
  ignore_errors: true
  changed_when: node_installed.rc != 0
  notify:
  - Install Node.js LTS

- include: install.yml
