# Location for the MPD database
db_file "~/.local/share/mpd/database"

# Send logs to the system journal
log_file "syslog"

# Set the music directory to use
music_directory "~/mus"

# Features

## Enable Playlists
playlist_directory "~/.local/share/mpd/playlists"

## Enable PID tracking
#pid_file "~/.local/share/mpd/mpd.pid"

## Enable local state
state_file "~/.local/share/mpd/state"

## Enable sticker DB
sticker_file "~/.local/share/mpd/sticker.sql"

# Refresh database whenever files in music_directory change
auto_update "yes"
auto_update_depth "0"

# Set MPD listener port
port "6600"

restore_paused "yes"

# If there's a symlink in the music folder, follow it
follow_inside_symlinks "yes"

# Set output to PulseAudio
audio_output {
  type "pulse"
  name "PulseAudio"
}
