---
- name: Ensure MPD is installed
  become: true
  package:
    name: mpd
    state: installed

- name: Ensure MPD directories exist
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: directory
  loop:
    - '.local/share/mpd'
    - '.local/share/mpd/playlists'
    - '.config/mpd'
    - 'music'

- name: Install MPD config
  copy:
    src: mpd.conf
    dest: "{{ ansible_env.HOME }}/.config/mpd/mpd.conf"
