---
- name: Install Noto Emoji fonts [Arch]
  become: true
  when: ansible_distribution == 'ArchLinux'
  community.general.pacman:
    name: noto-fonts-emoji,nerd-fonts-cascadia-code
    state: installed

- name: Install Noto Emoji fonts [Fedora]
  become: true
  when: ansible_distribution == 'Fedora'
  package:
    name: google-noto-emoji-color-fonts

- name: Ensure ~/.local/share/fonts/CascadiaCode exists
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.local/share/fonts/CascadiaCode"

- name: Download CaskaydiaCove fonts
  unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/CascadiaCode.zip
    remote_src: true
    dest: ~/.local/share/fonts/CascadiaCode

- name: Ensure ~/.config/fontconfig exists
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/fontconfig"

- name: Configure fontconfig
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/fontconfig/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
    force: true
    follow: false
  with_items:
    - 'fonts.conf'
    - 'fontconfig.conf'

- name: Refresh fontconfig cache
  command: fc-cache -fv
